services:
  broker:
    build: .
    ports:
      - "8080:8080"   # http: /healthz, /metrics
      - "7070:7070"   # tcp: frames
    volumes:
      - ./data:/data
      - ./configs:/configs

  prometheus:
    image: prom/prometheus
    volumes:
      - ./deploy/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9091:9090"
    depends_on:
      - broker

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
